apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: wine-lottery
  namespace: wine-lottery
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@halvorteigen.no
    push:
      branch: main
  update:
    path: ./k8s/apps/base/wine-lottery/
    strategy: Setters
