apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-secret.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml

images:
  - name: ghcr.io/halvorot/wine-lottery-website
    newTag: "20250324180437"
