apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: prod-podinfo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: ENVIRONMENT
              value: "production"
