---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgB8ZqmQX7OfQZ2Skz4cIgnH9ZjJqjsRpKOaGg0C37yWlpXhf+6GtTg6NW2p+m534/PCiBLlxkfGsrwolGC8BeOMS5N8ZHZKMfmvS/213pSpxvNU3GjhMx6M434jp3FymWDLCiDPUQyLF5IhUtEYgU/SoCkgDmNb/wra0bLTK2KHIRqRbx+m16JkdPl6nS/nLRNoCmZkGv3d4DbkGdwViIGFwKu+mRKwv75zMHoup4csQVB199gf56XZ9yGTEn/nBSWQxX2B5JOMooqDD1J91fsu2c3WFO0RkjHLTh1VsVGaoOwdTRXoAA62D9Tx+o+CF04Naq/xA/ERjeopqCZdInaUv0vGZyb9sPCsPQ07T9fV2yWNL1asO4fO0u8r8rCot49+MWYWK+ZhmQxYpV6pGQNKH+L/gyuextLQp+0QJ3ZQOqtU+ZE6vnZPYr0f48cSamA7jMhKNOIb9wGjlAweR2L6lfUQXNzmBLyZNgln0gJGYY/iyNVknAEoOqBUxt0kvSTUlPB7w2AnnmOK3CBoTAnpEWJ1BSozaYtz1NNKQAOhyxbUDFgtfFBT5WLCWmNl1e62NjFyfZJYKUXCopyzeGhbye1LiyrxQO4G7l156YtRyDFBzriMtv/Trbo0CJU3+MUqwUJdN2Uww8vDj5vXOuJkswAxL5cB9Ws3IuV8XOgtMtfmSUigeKqAZqed2Fwxyea+GP3peMRgoAKqSOvEa7cMi0W9+bWY2csA20Gl/AFumgJMFXVs0uHfOaDyAUg2M+M76Qjjn2+sNYjiX9falzjyEKf138SA7oN6RmVo9QpExmH33q7tROrgkb5RmfLDN9z2/0HAlkCUWNim5rLkXiKvoH+I+lbR5h73Xv8PaV3WsShVfSpbWHWMk97n0OSlAHYG60obxog1WRF1efs0kOHT/MRw5u0+85MOumDiq+TX+drQqtk4+bKq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-token
      namespace: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.2.1
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(TUNNEL_TOKEN)"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-tunnel-token
                  key: token