---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBZQlUZuwuTNweZgHENKVbLlEbNCCMNQ8jiF1uKPiEwJ9zYE0Sk5RFQUaGA/oqa9CO97IIHxKK6BXZjxLNfiJJQXTK5JdR2OI98+JnE7d5dOVu2WXfclL5TRyNQuhnmNChL3P2bHI2r2hF22xz6alqZruc3Gj4BP+ygf/JzOWDQdwCZwNTgjIz2s2TmyUWpLj8sAvZpLl1aD1ZI9Gz8RT2gOqYmt8OJMqn/pGKETjgXqn6cXZPczUCLnrMJUDQpiNA0e2r/GTnukIbIWSPz7k7dBIKSctB6HW+0Sfh9xcC6RvOzPF9RgEIh/tLz2T1EtLuLXF2EAAUReAwr26R+i1xPUkvOaqBNOPxws02SF+5+LCxTkG8E9awyEaIw0ey8jvSeswXnLryTpABS0LyxCh7HmCuYYZGzy/3MDNn+KZ2fMg7t9p+jsASxl4JCsBCtzRqRHJ/vlfBXF6nsj5jd8j2vRz9o+t9s80WDUz3wqlYMxndwwA0XIl4nuI2WQhsysF0J7zJJ/9bFP8kLyTI8eeEARs45hoIouefdUl4dVwB9YKmnwUh9H8vy3Ddu8b6KSC81ORr7zoygR2zOn/lzkx58RlHJl+gue5pw8iD9yJccQf/QsY1K7RVkyXVzobufZrLBMVTgLikgrTEkwtyJTtKuD+KiRqi7aPSXpYJtpIUZmZFFiL4wqMKiQcLQxTKpJ71jENASY8P/lgTPgVJDzLia9AQWkPa5fSPD7mYebotYVb+mNbp4ub7YDMMG0R87BK4uCXVLPB8ZnnK3/Os4tZPX0mzlk+iMa1ZozexR8CW6jjsYsF6KaAxTjWM4OX6a6YstfoFKK3r6QxpGkfuphDgIsOjQnTGeGM3eycrypLqXy52dc86gNFT8hDNKlxZ4BpE5zbx8EQ8BZgmUbojf2e9gOOmwL1dyeit/kToncKU9NHgxtqdTgJyY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-token
      namespace: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.2.1
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(TUNNEL_TOKEN)"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-tunnel-token
                  key: token