apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-ingress
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: podinfo.halvorteigen.no
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404 