---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logflare-secret
  namespace: supabase
spec:
  encryptedData:
    apiKey: AgAwurWJSkcO5PU6CzUFn0m2S9TIt5N0Hc0+xSvOYEhhQVViMs0pQFvPvuN2OQLunO+c/E1ScoA1XuGn2YEw/Zk27x4mxk2y1A5brzrjvLi6PD+tYFTcNIMYV4fMCIic99hQunDf5kdhE0WmcsqpdkAucPkP9Dz0UxBV8qPqfDQWIvCCN+YdyeQGCgBorCJtNAWph45fdRbSfDLURtbueJ946C4VWgFxXuWifCYy8xzIHj3lkEnFAKNDRXbbfXVw9YY6+8q8dCVkGyFDQZ9bOJXxvC5Q3Tunc+xT5R+qKEudzb29Et2mmGrLb0hev7mT9+Fj7Wirc/FZENFa90Sjdnc+dNycPsQpyRR0EjyP8ivcsiSxhbXyhL1VO8y55qXikbMsw3nDkNSh2EjiiJmy0eslpZeW+n2vEDnRMPENbjOef8n0uZK2mRrv3K0sZSK57GCilmFQs4E0z3e+EbHKobP5qHMtstn5Q++UMTxqEUobb6NuviJ/l42WmJ4bxtZ6Z9ULpO+RWOtVh3MsUBgThRNLevGNgIpqgQVlIOkpLhgAxOJZk002Jts/faZBfOLrNqAUT5YDZEmYXC5Zg7ry1pvvxKxHz9eGUdwSMJRG98mEghYKvtbRh1+xyPc/0sjQMyZWgLD36lLVcNBCKNmzWWaP5LJTSMbvN7CcQzpmxp1CSm/AZzNK405bsmn0/FduOvMa4pzNfxvSDGfSnkbc1LRIMDG/pQfXf+MkVqVJCQu3KG96Qq5B+SMgERJIjFbYCmTsIyQLTL2Zf9lz/HXKvAwGaHX/j+lMwRRdXhMOVZyu6Z3BD0+emWu21xuXyhYTt1zPsk2iCBbYRhDr9gH5XjjaD4ISxIP58hugWsWUGvRVag==
  template:
    metadata:
      creationTimestamp: null
      name: logflare-secret
      namespace: supabase
