---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teochenglim
  namespace: flux-system
spec:
  interval: 1h
  url: https://teochenglim.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  chart:
    spec:
      chart: supabase
      sourceRef:
        kind: HelmRepository
        name: teochenglim
      version: ">=0.1.3"
  interval: 1h0m0s
  targetNamespace: supabase
  valuesFrom:
    - kind: ConfigMap
      name: supabase-helm-values