---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: supabase
  namespace: flux-system
spec:
  interval: 1h
  url: https://supabase-community.github.io/supabase-kubernetes/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 1h
  targetNamespace: supabase
  chart:
    spec:
      chart: supabase
      version: ">=0.1.3"
      sourceRef:
        kind: HelmRepository
        name: supabase
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: supabase-helm-values