---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgC9kQ72faK7IpQvhVH3Z79+OH5KFc94E3UgDmUr612zQprebl+0HTYND8IUD3dSrMzuKSMXGf0/32hKgkQSPcaJycUur737lNGXEOsnlmLeYThbRzcv1mbby3l1Oz2LHmXccmhhUFpEzy8LA5SaamF5N+jZfludWLpAmbtuHWjXbtH/4hjtmOn4gjwx7BDjoNCvfpe7+8IB1dcY9QefHRN8OgSv/nnAA+cPUOUn1r0/uSfoHsC6jt0FSDNJhVOSlvFCnnOu3qWKZLztJYF5hOFlsQiGWV9kxAId3n4wzEzislW0Ucp6Pz/YxkAWD2inmFNa2HDQYvlJnrV/2yYK+nUg1Se+dlMBHSYxJFgXeZml9EAoYw56X6X3AABxD05wOFvasUKFmh2GJfdIhmAbT5qOoFOw4V8gEW1M1zZa1YKB2mM9UDUz2nocpAL/0vQ0D5+SQgqb+NZng4ZEwEqu8QgbMVQd7b+Bv+n/UMC4mjnGcwukD6Hy6dz2jNhUw2wCHtpeM4RKrIqy6Bi/vANhxn2MLVJb0wB90RxHPnfzcUZGXL/GyWDdxvpwLmc3k1inuCSY3ulFLvK71vPh6zfiR40TpzHnaPQvQtMkGRHGGl0oLZBdQN6WYYqp+wZZVJdkSrgZxcxzto7ZXzwFRi9o2Yy5siH7T3oWbkb1CfZw0N7Z+4rVadEMGx537PE9zBa5lW8VMqKLkjWerbzkz88ttfqkmnhch1E023F25gwrLYmgFU47/QBC9+F5x3ZrSQB44sZhLc8fmcr8kj75DqzbWvKik8crkIzY87sYr+vmMg0/Mzb6qEbfqvNKf/gi/khE74MKHJWR1aWifdg+0AH6UoZI9QGJtblngnTr+CtBWjUdvV/DPkoLjCjUBWjqp1Fbiq+5xYWgwfC2990iC9zysN7lGuhYYDI6+3M6n5qPb9mrwglvApermaSV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-token
      namespace: cloudflared