---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgBetc3KS6FFuGd39U9Em5TIUas5atd+YZvyIHlR4PgU4qO4/iBa/6WmrYFFWiyyZDhEE442DKh1duvRU77PKCKMI0sAuaYih78ErIf03NTpFfbpyhPk7ZQS083zlE2e7dUwSegbewzBAXq8SO28dpdDK0INklMt1b2GOBjWFndp2nPn/XoaT/DaJW3f7m2/DblWQ6MZsRtf18Y+H9Cr6bqrshhmND0doAtjtKpAgLtuZ3kzESGnzIgFZ5A7IKWZAx9u5mr/DoBQF6Mt3dyhqJJypZXvPWlBrE+ZcSyxGS/NToDfq6jhlRTvooA7LEWcxhOpkMBncSJ7AT9bhXeLcrfgBsJIa7ssp+qlUZSbO9xXsIF77M3MY/af5cXYaz4BNAa5gf1N7anqE+3UP5WuA/8FTaQHAW7zmm45aFgwzTnUges9qRjb6eJiBP8QrL5RJkcOfAOjTVqsG4PEqhiHxCXTlVLAmgwsN1LOet7EJ+6D6iDKAadzfITh0UkzJgNUH2pNtNDflzypyjrMQ9h9iSeUOHvboKswYCp3XL3EbC+9htPdmAqmp41+Ct/7tGriBxGLwP/2V7j8IX2EpDxLO+MsSBqNcfCANzvKY2gpHhmk8NJ8oy1KJgmvzS05+bPA5BjuCF7K5iWCrlcGZ4Bc33vLdAnHv5SXYACEHfbWzjizd7BewmmFJOyVv5MJCyFU3CS8WDer32k3/Er0yZclLyMBozU8U2wI5JxkK+mddJLrAEm58aVkjJP2
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
