apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  settings.yaml: |
    title: "Homelab | Halvor Ødegård Teigen"
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/halvorot
              icon: "si-github"
    - Social:
        - LinkedIn:
            - abbr: in
              href: https://www.linkedin.com/in/halvor-teigen/
              icon: "si-linkedin"
  services.yaml: |
    - Apps:
        - Wine Lottery website:
            icon: "si-wine-#800000"
            href: "https://vinlotteri.halvorteigen.no"
            namespace: wine-lottery
            app: wine-lottery
        - Cert Portal website:
            icon: "si-c-#3b82f6"
            href: "https://certportal.halvorteigen.no"
            namespace: cert-portal
            app: cert-portal
        - Excalidraw:
            icon: "si-excalidraw-#6965DB"
            href: "https://excalidraw.halvorteigen.no"
            namespace: excalidraw
            app: excalidraw

    - Backend Services:
        - Grafana:
            icon: "si-grafana-#F46800"
            href: "https://grafana.halvorteigen.no"
            namespace: monitoring
            app: monitoring
        - Minio:
            icon: "si-minio-#C72E49"
            href: "https://minio.halvorteigen.no"
            namespace: minio
            app: minio
        - Longhorn:
            icon: "https://avatars.githubusercontent.com/u/51335366?v=4"
            href: "https://longhorn.halvorteigen.no"
            namespace: longhorn
            app: longhorn
        - Proxmox:
            href: "https://proxmox.halvorteigen.no"
            icon: "si-proxmox-#E57000"
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
        units: metric
    - search:
        provider: google
        target: _blank
  docker.yaml: ""