apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - cluster-role.yaml
  - config-map.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml
  - service-account.yaml
