apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-portal
  template:
    metadata:
      labels:
        app: cert-portal
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cert-portal
          image: ghcr.io/halvorot/cert-portal:20250728220313
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
