---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBWwpQPMwxWInVZC7fsP5YrWSBwrPOxjfx5l12BTjRIL+KLvEBjhauvU9P7blzZHBKV1CM+nsY+eY/CWuA5Z2AA58Af9D/BVxc7pNgozNvGHKC0BtQT4NuiziOHr0Dq0huxouhdROpPQPjJawlsLw0zWEiWpi3YoBQt2BgK9Ug67oT4yPaan4f3XjTs47EmQHN5DLrJ+xiC1sawClUaXgo9Zv5D0a7TXtT8SCdkMPgFYj/AcaDJqhGlqRtjuO9v8AzbOsEcmOB2UB++geK610BDMsa1XdXBW4Hr9b2hAQERj+ZucZ74nJljH/pG9Es1rhvIMfqBW2G0dqkS+abPJXhLkT7G7dzhJQmO4j5490ykHlyplcJJt7utiedtq/ZZNz37tBx14I6cRUTs/UbVti9S77JK7KKAJZMS0i6UPEvTjLbngUfhV7sHoAfLuMh8BqnsiGj7+ubhBk2LKv+e877CIHcVKu9f4V0FK8tQ0nCqoqKH21fBYwzGIF/RU2WI8+4O314+amx+Y4Omx0CUl/lveReaagE+IZsDuitQGIa9swP2vEcgkIIvTjBnwgELSVESmP6ddsAmEwIjUqrX7TKXsJTvBdsZEHpseJuQAPVRw79ybxnDgE1nlc03Wi5MUmeRLWj97nROKJlhp4GRQ9JzMOiWW5bTsXO8x+kC9eSBJGBcwTAz4DUae6NvxEwA497srA5guo/n9Sz0Kxe1EBLy+x+UJqFwOsSRdig13sP0f6f3FS5f0XPzGgpjUDjdili++3VGIZgFLJIds7Ud2p8nmL8RJHUpeJuVsRf55nQYbiqI3bHxKEzbOPC7aT1bvCVTiGdIRdZCcby7fOCLGui27DVVWLGEAv8Nx6ysw/zA3aU/Yrj+NH4Rz0jn03ofxXqS5VhV0VeSo9ZneXPC1cmdkwhhOuX2Ped1JFE+Zk2xFpI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: cert-portal
    type: kubernetes.io/dockerconfigjson
