---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: halvorot@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
      - selector:
          dnsZones:
            - "halvorteigen.no"
        dns01:
          cloudflare:
            email: halvorot@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: cloudflare_api_token