---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBPdLmdeUQuU+JSsS1ovX9EO2a0N+R85JZgoUBdS2xg9aOhf2wo9F99eBca/l0nDhOszRIBVN/jS2Tf2nNJbbUD5+sm63mOtqpLCFPv/17CU3sP4G3v3YQrrJky8UwC9H8sVoJ+TrBJgbE17TURiTR3S6koJ1e9rkxXGSVcb4uwyr/j5PIn5tdgUdgXSIXXQQQMs5uKaIpimzkMDxpLs1jO3b+EXHotXzA5rb1XfYnf8lgJRT1mRKjdVOESiPBG4Kt/2W0QlwA9842zQDXioSqPZBJ8id0++NpCaD9kcABZHVgvgOJLMgGp9BN9ITWUG0dDGeqK11gVecG6M/s1hJSG4hmRaXN3U4vvvAvo06TSFRRmpzz3eGnWGKqO3y8QCxnf3aKxAHp4NHYA0AtSgDaa9sZkVApFC+4FnxyhO6Ce0vgkSoVVbKE7zDzgxGhlcKyXNUyp0iyZu81d/huF2zeuPJc8831vS1IxmVx72DsuqhSDenrM3/Wp/IVFOfA73GfvyUh0NO8E+WPaw1WAANx26UJlhaeeVdYRYSNDi3Anx5hj7B68qHhFkQ3XNOo0C+10vA9zX8zU/iSV/EuPw/DmsiY+uUpV42UFx2Z4KbblgkN1pyyqXqgaUIEViDPD4xb7j5QqNe09xJ/a8JPug9h7o7TRh/b56YwqKI4YGqlMOy0p83ItbreDndmN31LljX6PPGbn2dsJMB1JBdn8kW0DLEyzlRYBl8bG2EKbd40hSjQTPB7DEQAc
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: external-dns
