apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: "8.7.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  values:
    ## @param sources [array] K8s resources type to be observed for new DNS entries by ExternalDNS
    ##
    sources:
      - crd
      # - service
      # - ingress
      # - contour-httpproxy
    ## @param provider DNS provider where the DNS records will be created.
    ## Available providers are:
    ## - akamai, alibabacloud, aws, azure, azure-private-dns, cloudflare, coredns, designate, digitalocean, google, hetzner, infoblox, linode, rfc2136, transip, oci
    ##
    provider: cloudflare
    ## Cloudflare configuration to be set via arguments/env. variables
    ##
    cloudflare:
      ## @param cloudflare.apiToken When using the Cloudflare provider, `CF_API_TOKEN` to set (optional)
      ##
      apiToken: ""
      ## @param cloudflare.apiKey When using the Cloudflare provider, `CF_API_KEY` to set (optional)
      ##
      apiKey: ""
      ## @param cloudflare.secretName When using the Cloudflare provider, it's the name of the secret containing cloudflare_api_token or cloudflare_api_key.
      ## This ignores cloudflare.apiToken, and cloudflare.apiKey
      ##
      secretName: "cloudflare-api-token-secret"
      ## @param cloudflare.email When using the Cloudflare provider, `CF_API_EMAIL` to set (optional). Needed when using CF_API_KEY
      ##
      email: "halvorot@gmail.com"
      ## @param cloudflare.proxied When using the Cloudflare provider, enable the proxy feature (DDOS protection, CDN...) (optional)
      ##
      proxied: true
      ## @param cloudflare.dnsRecordsPerPage Number of DNS records to fetch per page. (optional)
      ## When using the Cloudflare provider, specify how many DNS records listed per page, max possible 5,000 (default: 100)
      ##
      dnsRecordsPerPage: 100
    ## Options for the source type "crd"
    ##
    crd:
      ## @param crd.create Install and use the integrated DNSEndpoint CRD
      ##
      create: true