apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  selector:
    app: podinfo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9898
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9898