apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/podinfo/overlays/production  # Path to the overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # Should match the GitRepository managing your repo
  validation: client
