apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.8.0
          ports:
            - containerPort: 8080
