---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller
  ref:
    tag: latest
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: ">=11.6.0"
      sourceRef:
        kind: nginx-ingress-controller
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nginx-ingress-controller