---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: ">=1.8.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  targetNamespace: longhorn
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    csi:
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 1
    defaultSettings:
      defaultDataPath: /mnt/data/longhorn
    persistence:
      defaultClass: true
    longhornUI:
      replicas: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - longhorn.halvorteigen.no
      secretName: longhorn-halvorteigen-tls
  rules:
    - host: longhorn.halvorteigen.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80

